name: tag

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest=$(git tag --sort=-version:refname | head -n 1)
          echo "Latest tag: $latest"
          echo "latest_tag=${latest}" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          latest=${{ steps.get_tag.outputs.latest_tag }}
          if [[ -z "$latest" ]]; then
            echo "new_tag=v0.1.0" >> $GITHUB_OUTPUT
          else
            ver=${latest#v}
            IFS='.' read -r major minor patch <<< "$ver"
            patch=$((patch + 1))
            echo "new_tag=v$major.$minor.$patch" >> $GITHUB_OUTPUT
          fi

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
